### PR TITLE
Add linux compilation

### PR DESCRIPTION
**Pull request by leguilc**
We added the compilation on linux (CMake)
and included other algorithms found in the Internet

### CODE REVIEW

**Comment by gaspardpetit** [comment]
Thanks, I particularly appreciate the table/graph generation.  Do you have details about where the Adition implementation came from? It's pretty good - ranked first (now second since I added the chromium's `modp_b64` implementation).

**Comment by alexglyde** [comment]
@leguilc and @gaspardpetit, any update on where the Adition implementation came from? Considering using it but would like to vet the original (looking for updates, tests, etc).

**Comment by gaspardpetit** [comment]
Hi @alexglyde - Unfortunately no, I did not hear back so I am not sure about who the author is and what the license would be. I imagine the owners at https://github.com/ADITION might know

**Comment by alexglyde** [comment]
Thanks @gaspardpetit, I'll check that github repo out - didn't even come up in my search when I was looking for the original.

**Comment by leguilc** [comment]
Sorry for the late answer, yes the code had been written for and by Adition (https://www.adition.com/) and its  repo https://github.com/ADITION  presents some of the open source project my company participate.

When we used  @gaspardpetit repo to make our research on base64, we decided to release our code at the same time.

Once again, you are correct and I did not include any license on that code, I am kind of lost with all the licenses, so I will have to ask my manager which one he wants to use. (but IMO it should be the most permissive one).

**Pull request merged**
